=== Sperper/UD4/XMLRepUD4/Act5/Alumnado.dtd
<!ELEMENT CFGS (alumno*)>
<!ELEMENT alumno (NIF, resultado, observaciones?, (IP | MAC))>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ATTLIST resultado resultado (apto | noApto) #REQUIRED>
<!ELEMENT IP (#PCDATA)>
<!ELEMENT MAC (#PCDATA)>

=== Sperper/UD4/XMLRepUD4/Act5/Alumnado.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CFGS SYSTEM "Alumnado.dtd">

<CFGS>
    <alumno>
        <NIF></NIF>
        <resultado resultado="apto"></resultado>
        <observaciones></observaciones>
        <MAC></MAC>
    </alumno>
    <alumno>
        <NIF></NIF>
        <resultado resultado="noApto"></resultado>
        <IP></IP>
    </alumno>
</CFGS>
