=== Sperper/UD4/XMLRepUD4/Act7/Editorial.dtd
<!ELEMENT Informe (cabecera*, datos*)>
<!ELEMENT cabecera (descripcion, fechaInforme+)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fechaInforme (#PCDATA)>
<!ELEMENT datos (region*)>
<!ELEMENT region (zona, trimestre*)>
<!ELEMENT zona (#PCDATA)>
<!ELEMENT trimestre (librosVendidos)>
<!ATTLIST trimestre numero (1 | 2 | 3 | 4) #REQUIRED>
<!ELEMENT librosVendidos (#PCDATA)>

=== Sperper/UD4/XMLRepUD4/Act7/Editorial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Informe SYSTEM "Editorial.dtd">
<Informe>
    <cabecera>
        <descripcion>informe de ventas para las regiones Norte, Centro y Sur</descripcion>
        <fechaInforme>30/12/2009</fechaInforme>
    </cabecera>
    <datos>
        <region>
            <zona>Norte</zona>
            <trimestre numero="1">
                <librosVendidos>24000</librosVendidos>
            </trimestre>
            <trimestre numero="2">
                <librosVendidos>38600</librosVendidos>
            </trimestre>
            <trimestre numero="3">
                <librosVendidos>NO_INFO</librosVendidos>
            </trimestre>
            <trimestre numero="4">
                <librosVendidos>NO_INFO</librosVendidos>
            </trimestre>
        </region>
        <region>
            <zona>Centro</zona>
            <trimestre numero="1">
                <librosVendidos>NO_INFO</librosVendidos>
            </trimestre>
            <trimestre numero="2">
                <librosVendidos>16080</librosVendidos>
            </trimestre>
            <trimestre numero="3">
                <librosVendidos>25000</librosVendidos>
            </trimestre>
            <trimestre numero="4">
                <librosVendidos>29000</librosVendidos>
            </trimestre>
        </region>
        <region>
            <zona>Sur</zona>
            <trimestre numero="1">
                <librosVendidos>27000</librosVendidos>
            </trimestre>
            <trimestre numero="2">
                <librosVendidos>31400</librosVendidos>
            </trimestre>
            <trimestre numero="3">
                <librosVendidos>40100</librosVendidos>
            </trimestre>
            <trimestre numero="4">
                <librosVendidos>30000</librosVendidos>
            </trimestre>
        </region>
    </datos>
</Informe>
