=== Sperper/UD4/XMLRepUD4/Act2/Concesionario.dtd
<!ELEMENT Concesionario (coche*)>
<!ELEMENT coche (codigoDeCoche, marca, modelo, matricula, potencia, plazas, numeroDePuertas)>
<!ELEMENT codigoDeCoche (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT numeroDePuertas (#PCDATA)>

=== Sperper/UD4/XMLRepUD4/Act2/Concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Concesionario SYSTEM "Concesionario.dtd">
<Concesionario>
    <coche>
        <codigoDeCoche>IJCLMNJHG89736589</codigoDeCoche>
        <marca>Ferrari</marca>
        <modelo>Ferrari SF90 Stradale</modelo>
        <matricula>7865 ETF</matricula>
        <potencia>1000CV</potencia>
        <plazas>2</plazas>
        <numeroDePuertas>2</numeroDePuertas>
    </coche>
</Concesionario>

=== Sperper/UD4/XMLRepUD4/Act3/Concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Concesionario SYSTEM "/Users/sperper2907/Desktop/1%20DAW/Lenguaje%20de%20marcas/UD4/XMLRepUD4/Act2/Concesionario.dtd">
<Concesionario>
    <coche>
        <codigoDeCoche>IJCLMNJHG89736589</codigoDeCoche>
        <marca>Ferrari</marca>
        <modelo>Ferrari SF90 Stradale</modelo>
        <matricula>7865 ETF</matricula>
        <potencia>1000CV</potencia>
        <plazas>2</plazas>
        <numeroDePuertas>2</numeroDePuertas>
    </coche>
    <coche>
        <codigoDeCoche>IKCLMNJOG83736589</codigoDeCoche>
        <marca>Lamborghini</marca>
        <modelo>Urus S</modelo>
        <matricula>5287 PDP</matricula>
        <potencia>666CV</potencia>
        <plazas>5</plazas>
        <numeroDePuertas>5</numeroDePuertas>
    </coche>
</Concesionario>
